server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Vpp2000/configuration-server-project
          search-paths: config-data
  application:
    name: configuration-server
